language: shell
os: linux
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
    - git clone https://github.com/docker-library/official-images.git official-images

script:
    - REPO_NAME=openvpn-server
    - IMAGE=harlov91/openvpn-server
    - IMAGE_VERSION=v1
    - docker build -t "$IMAGE:$IMAGE_VERSION" .
    - docker push $DOCKER_USERNAME/$REPO_NAME:$IMAGE_VERSION

after_script:
    - docker images
